spring:
  datasource:
    url: jdbc:mysql://localhost:6603/bookdb?useUnicode=tru&characterEncoding=UTF-8&serverTimezone=UTC
    username: bookadmin
    password: mysql
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
