spring:
  jpa:
#    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: mysql
  liquibase:
    change-log: db/changelog/changelog-master.xml

#Show bind values
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.transaction.interceptor: TRACE
    org.hibernate.sql: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
